pipistrellVote/protected/admin/controllers/UploadController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class UploadController extends CController {

    public $view = 'index';
    public $model = 0;
    public $domId = '';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter - Uploadfile'
            )
        );
    }

    public function actionIndex() {
        $this->model = isset($_GET['model']) && !empty($_GET['model']) ? $_GET['model'] : 0;
        $this->view = isset($_GET['view']) && !empty($_GET['view']) ? $_GET['view'] : 'index';
        $this->domId = isset($_GET['id']) && !empty($_GET['id'])?$_GET['id']:'';
        $this->renderPartial($this->view, array(
            'upPath' => CHtml::normalizeUrl(array('upload/uploadfile')),
            'fname' => $_GET['fname']
        ));
    }

    public function actionUploadfile() {
        
        if (!empty($_POST)) {
            $file_n = '';
            if (isset($_POST['fileName'])) {
                $file_n = $_POST['fileName'];
            } else if (isset($_GET['fileName'])) {
                $file_n = $_GET['fileName'];
            }
            $POST_MAX_SIZE = ini_get('post_max_size');
            $unit = strtoupper(substr($POST_MAX_SIZE, -1));
            $multiplier = ($unit == 'M' ? 1048576 : ($unit == 'K' ? 1024 : ($unit == 'G' ? 1073741824 : 1)));

            if ((int) $_SERVER['CONTENT_LENGTH'] > $multiplier * (int) $POST_MAX_SIZE && $POST_MAX_SIZE) {
                header("HTTP/1.1 500 Internal Server Error");
                echo "POST exceeded maximum allowed size.";
                exit(0);
            }

            $save_path = dirname(Yii::app()->getBasePath()) . "/" . $file_n . "/";
            if (!file_exists($save_path)) {
                mkdir($save_path);
            }
            $upload_name = "Filedata";
            $max_file_size_in_bytes = 2147483647;    // 2GB 
            $extension_whitelist = array("php", "gif", "jpg", "png");
            $valid_chars_regex = '.A-Z0-9_ !@#$%^&()+={}\[\]\',~`-';

            $MAX_FILENAME_LENGTH = 260;
            $file_name = "";
            $file_extension = "";
            $uploadErrors = array(
                0 => "0",
                1 => "1",
                2 => "2",
                3 => "3",
                4 => "4",
                6 => "5"
            );
          
            if (!isset($_FILES[$upload_name])) {
                $this->HandleError("No upload found in \$_FILES for " . $upload_name);
                exit(0);
            } else if (isset($_FILES[$upload_name]["error"]) && $_FILES[$upload_name]["error"] != 0) {
                $this->HandleError($uploadErrors[$_FILES[$upload_name]["error"]]);
                exit(0);
            } else if (!isset($_FILES[$upload_name]["tmp_name"]) || !@is_uploaded_file($_FILES[$upload_name]["tmp_name"])) {
                $this->HandleError("Upload failed is_uploaded_file test.");
                exit(0);
            } else if (!isset($_FILES[$upload_name]['name'])) {
                $this->HandleError("File has no name.");
                exit(0);
            }

            $file_size = @filesize($_FILES[$upload_name]["tmp_name"]);
            if (!$file_size || $file_size > $max_file_size_in_bytes) {
                $this->HandleError("File exceeds the maximum allowed size");
                exit(0);
            }

            if ($file_size <= 0) {
                $this->HandleError("File size outside allowed lower bound");
                exit(0);
            }

            $file_name = preg_replace('/[^' . $valid_chars_regex . ']|\.+$/i', "", basename($_FILES[$upload_name]['name']));
            if (strlen($file_name) == 0 || strlen($file_name) > $MAX_FILENAME_LENGTH) {
                $this->HandleError("Invalid file name");
                exit(0);
            }
            
            $path_info = pathinfo($_FILES[$upload_name]['name']);
            $file_extension = $path_info["extension"];
            $is_valid_extension = false;
            foreach ($extension_whitelist as $extension) {
                if (strcasecmp($file_extension, $extension) == 0) {
                    $is_valid_extension = true;
                    break;
                }
            }

            if (!$is_valid_extension) {
                $this->HandleError("1444");
                exit(0);
            }

            $file_name = date("YmdHis").'_'.rand(10000, 99999).'.'.$path_info["extension"];
            if (!@move_uploaded_file($_FILES[$upload_name]["tmp_name"], $save_path . $file_name)) {
                $this->HandleError("文件无法保存");
                exit(0);
            }

            echo $file_name;
            return;
        }
    }

 

}

?>

pipistrellVote/protected/admin/controllers/WidgetController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class WidgetController extends CController {
   public $isType = 0;
   public $isSmallType = 0;
   public $row = 10;
   public $page = 1;
   public $totalPage = 0;
   public $total = 0;
   public $layout='application.admin.views.layouts.main';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter'
            )
        );
    }

    public function actionIndex() {
        $this->page = isset($_GET['page'])&&!empty($_GET['page'])?$_GET['page']:1;
        $this->isType = 2;
        $this->isSmallType = $_GET['isSmallType'];
        $this->render('widgetShow',array(
            'data'=>$this->_getData()
        ));
    }
    private function _getData(){
        $limit = ' limit '.(($this->page-1)*$this->row).','.$this->row;
        $where = adminSys::_whereWork($_POST);
        $where = empty($where)?' where isSys="0" ':' and isSys = "0" ';
        $sql = 'select * from {{widget}} '.$where.$limit;
        $sql1 = 'select count(*) as count_num from {{widget}} '.$where;
        $data = array();
        $data[0] = Yii::app()->db->createCommand($sql)->queryAll();
        $data[1] = Yii::app()->db->createCommand($sql1)->queryAll();
        $this->totalPage = ceil($data[1][0]['count_num']/$this->row);
        $this->total = $data[1][0]['count_num'];
        return $data[0];
    }
    public function actionEdit(){
        if(empty($_GET['wid']))$this->redirect (array('site/error','msg'=>'ID不能为空！'));
        $data = Widget::model()->findByPk($_GET['wid']);
        $this->render('widgetEdit',array(
            'data'=>$data,
            'title'=>'编辑挂件'
        ));
    }
    public function actionPutedit(){
        if(IS_POST){
            if(empty($_POST['wid']))$this->redirect (array('site/error','msg'=>'ID不能为空！'));
            $widget = Widget::model()->findByPk($_POST['wid']);
            if($widget->widgetNameCn != $_POST['widgetNameCn'] && !empty($_POST['widgetNameCn']))$widget->widgetNameCn = $_POST['widgetNameCn'];
            if($widget->widgetFile != $_POST['widgetFile'] && !empty($_POST['widgetFile']))$widget->widgetFile = $_POST['widgetFile'];
            if($widget->ismobile != $_POST['ismobile'] && !empty($_POST['ismobile']))$widget->ismobile = $_POST['ismobile'];
            if($widget->enable != $_POST['enable'] && !empty($_POST['enable']))$widget->enable = $_POST['enable'];
            if($widget->description != $_POST['description'] && !empty($_POST['description']))$widget->description = $_POST['description'];
            $widget->update();
            echo 1;
        }
    }
    public function actionAdd(){
        if(!isset($_GET['step']) || empty($_GET['step']))$_GET['step'] = 1;
        $step = $_GET['step'];

        if($step != 1){
            $step = isset(Yii::app()->session['newWidgetStep'])?$step:1;
            if(!isset(Yii::app()->session['uploadModel']))Yii::app()->session['uploadModel'] = '$.widgetAdd.isUploadC()';
        }
        
        $this->render('add_step_'.$step,array(
            'step'=>$step
        ));
    }
    public function actionClear(){
        unset(Yii::app()->session['uploadModel']);
        unset(Yii::app()->session['newWidgetStep']);
    }
    public function actionPutInDb(){
        if(!IS_POST)return;
        $widget = Widget::model()->find(' widgetName = :_widgetName ',array(':_widgetName'=>$_POST['widgetName']));
        if($widget){echo 2;return;}
        $widget = New Widget();
        if(!empty($_POST['widgetName']))$widget->widgetName = $_POST['widgetName'];
        if(!empty($_POST['widgetNameCn']))$widget->widgetNameCn = $_POST['widgetNameCn'];
        if(!empty($_POST['widgetFile']))$widget->widgetFile = $_POST['widgetFile'];
        if(!empty($_POST['description']))$widget->description = $_POST['description'];
        if(!empty($_POST['ismobile']))$widget->ismobile = $_POST['ismobile'];
        if(!empty($_POST['enable']))$widget->enable = $_POST['enable'];
        $bak = $widget->save();
        if(!$bak)return '';
        Yii::app()->session['newWidgetStep'] = $widget->widgetName;
        echo $bak;
    }
    public function actionSqldetail(){
        if(empty($_GET['wid']))return;
        $widget = Widget::model()->findByPk($_GET['wid']);
        $addfileds = require_once 'addfileds_'.$widget->tableName.'.php';  
       $addCN = require_once 'addfiledsCn_'.$widget->tableName.'.php';
        $this->render('sqldetail',array(
            'widgetData'=>  $widget,
            'addfileds'=>$addfileds,
            'addCN'=>$addCN
        ));
    }
    public function actionDeletField(){
        if(empty($_POST['wid']))return;
         
        $widget = Widget::model()->findByPk($_POST['wid']);
        $arr = $_POST['sqlcheck'];
        eval('$addfileds = array('.$_POST['addfileds'].');');
        eval('$addCN = array('.$_POST['addCN'].');');
        $str = '';
        $arrCN = '';
        $arrFileds = '';
        if(!empty($arr)){
        foreach($arr as $v){
            if(!empty($str))$str .= ',';
            $str .= $v;
            $arrFileds .= '"'.$v.'"=>"'.$addfileds[$v].'",';
            $arrCN .= '"'.$v.'"=>"'.$addCN[$v].'",';
         }
         $arrFileds = '<?php return array('.$arrFileds.');';
         $arrCN = '<?php return array('.$arrCN.');';
        }else{
            $arrFileds = '<?php return array();';
            $arrCN = '<?php return array();';
        }
         $path = dirname(__FILE__) . DIRECTORY_SEPARATOR . '..'.DIRECTORY_SEPARATOR.'addfileds'.DIRECTORY_SEPARATOR;
         file_put_contents($path.'addfileds_'.$widget->tableName.'.php', $arrFileds);
         file_put_contents($path.'addfiledsCn_'.$widget->tableName.'.php', $arrCN);
         $widget->Attribute = $str;
         $bak = $widget->update();
         echo '<script>parent.backMsg("'.$bak.'");</script>';
    }
    public function actionAddFildes(){
        if(empty($_GET['wid']))$this->redirect (array('site/index'));
        $this->render('addFileds',array(
            'wid'=>$_GET['wid']
        ));
    }
    public function actionAddSqlFiled(){
        if(empty($_POST['wid']))return;
        $widget = Widget::model()->findByPk($_POST['wid']);
        $Attr = $this->_filedAttr($_POST['Attr']);
         
        $addfileds = require_once 'addfileds_'.$widget->tableName.'.php';  
       $addCN = require_once 'addfiledsCn_'.$widget->tableName.'.php';
       $addfileds[] = 1;
      
       $str = var_export($addfileds,true);
       echo $str;return;
        $sql = 'alter table {add'.$widget->tableName.'} add '.$_POST['fName'].' '.$Attr.' ';
    }
    private function _filedAttr($name){
        switch($name){
            case 'radio':
                $a = 'tinyint(4)';
                break;
            case 'date':
                $a = 'int(11)';
                break;
            case 'htmltext':
                $a = 'mediumtext(0)';
                break;
            case 'upload':
                $a = 'varchar(255)';
                break;
            case 'number':
                $a = 'float(0)';
                break;
            case 'text':
                $a = 'varchar(50)';
                break;
        }
        return $a;
    }
}

?>

pipistrellVote/protected/admin/views/widget/addFileds.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/addFileds.js"></script>
<div id="main-content">
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;">添加字段</h3>
            <input class="button" style="float:right; margin-top: 7px; margin-right: 15px;" type="submit" onclick="$.addfileds.putData('<?php echo CHtml::normalizeUrl(array('widget/addSqlFiled')); ?>');" value="保存">
            <div class="clear"></div>
        </div>

        <div class="content-box-content">
            <div class="tab-content default-tab" style="display: block;">
                <form method="post" onsubmit ="return false;">
                    <input type="hidden" id="wid" value="<?php echo $wid; ?>" />
            <fieldset>
                <p>
                    <label>字段名</label>
                    <input  class="text-input small-input" type="text" id="filedName"  onbeforepaste="clipboardData.setData('text',clipboardData.getData('text').replace(/[\u4e00-\u9fa5]/g,''))" onkeyup="this.value=this.value.replace(/[\u4e00-\u9fa5]/g,'')"  /><span class="input-notification attention png_bg">不能为中文！</span>
                </p>
                <p>
                    <label>提示文字</label>
                    <input  class="text-input small-input" type="text" id="filedNameCN"/>
                </p>
                <div style="display:block;overflow: hidden;">
                    <label>属性</label>
                    <div  onclick="$.addfileds.changeAttr(this,'radio');" class="notification information png_bg" style="width:13%; height:100px; overflow: hidden; float: left; margin-left: 15px;">
                  <div><h5>radio</h5><br /><small class="small">单选框<small></div>
                 </div>
                    <div  onclick="$.addfileds.changeAttr(this,'date');" class="notification information png_bg" style="width:13%; height:100px; overflow: hidden; float: left; margin-left: 15px;">
                  <div><h5>date</h5><br /><small class="small">日期选择<small></div>
                 </div>
                    <div  onclick="$.addfileds.changeAttr(this,'htmltext');" class="notification information png_bg" style="width:13%; height:100px; overflow: hidden; float: left; margin-left: 15px;">
                  <div><h5>htmltext</h5><br /><small class="small">详情录入(可编辑文本框)<small></div>
                 </div>
                    <div  onclick="$.addfileds.changeAttr(this,'upload');" class="notification information png_bg" style="width:13%; height:100px; overflow: hidden; float: left; margin-left: 15px;">
                  <div><h5>upload</h5><br /><small class="small">上传控件<small></div>
                 </div>
                 <div  onclick="$.addfileds.changeAttr(this,'number');" class="notification information png_bg" style="width:13%; height:100px; overflow: hidden; float: left; margin-left: 15px;">
                  <div><h5>number</h5><br /><small class="small">数字输入<small></div>
                 </div>
                    <div  onclick="$.addfileds.changeAttr(this,'text');" class="notification information png_bg" style="width:13%; height:100px; overflow: hidden; float: left; margin-left: 15px;">
                  <div><h5>text</h5><br /><small class="small">文本输入框<small></div>
                 </div>

                </div>
            </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>

pipistrellVote/protected/admin/views/widget/add_step_1.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/widget_add.js"></script>
<?php $this->beginContent('//layouts/widget_step',array('step'=>$step));
            echo $content;
            $this->endContent(); ?>

<div id="main-content">
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;">新增挂件  → 录入挂件信息</h3>
        </div>
        
        <div class="content-box-content">
            <form id="step_1_form" onsubmit="return false;">
                
                <p>
              <label>挂件名称</label>
              <input class="text-input small-input" type="text" id="widgetName" name="small-input">
              <span class="input-notification attention png_bg">英文名称</span></p>
                <p>
              <label>挂件名称</label>
              <input class="text-input small-input" type="text" id="widgetNameCn" name="small-input">
              <span class="input-notification attention png_bg">中文名称</span></p>
                <p>
              <label>显示文件名</label>
              <input class="text-input small-input" type="text" id="widgetFile" name="small-input">
              <span class="input-notification attention png_bg">如：填写 product 则对应( product.php:列表页  productView.php：详情页 ) </span></p>
                <p >
              是否支持移动端：
              <input type="radio" name="ismobile" checked="checked" value ="1" >
              是
              <input type="radio" name="ismobile" value ="0" >
              否</p>
                <p >
              是否启用：
              <input type="radio" name="enable" checked="checked" value ="1" >
              是
              <input type="radio" name="enable" value ="0" >
              否</p>
                <p>
            <label>挂件描述：</label>
            <textarea class="text-input textarea" id="description" name="textfield"  rows="5" style="display: block;"></textarea>
        </p>
                <p>
                    <input class="button" type="submit"  onclick="$('#step_1_form')[0].reset();" value="重置">&nbsp;&nbsp;<input class="button" type="submit"  onclick="$.widgetAdd.infoNextStep();" value="下一步">
                </p>
            </form>
        </div>
    </div>
</div>

pipistrellVote/protected/admin/views/widget/add_step_2.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/widget_add.js"></script>
<?php $this->beginContent('//layouts/widget_step',array('step'=>$step));
            echo $content;
            $this->endContent(); ?>

<div id="main-content">
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;">新增挂件 → 上传控制器文件</h3>
        </div>
        
        <div class="content-box-content">
            <div class="notification information png_bg">
      <div>注意上传文件格式必须为*.php</div>
    </div>
            <form id="step_1_form" onsubmit="return false;">
                 <input type="hidden" id="isUpload" value="0" />
                 <p>
                     <iframe border="no" width="100%" height="100%" src="<?php echo CHtml::normalizeUrl(array('upload/index','fname'=>'widget','model'=>1)); ?>" ></iframe>
                 </p>
                <p>
                    <input class="button" type="submit"  onclick="$('#step_1_form')[0].reset();" value="重置">&nbsp;&nbsp;<input class="button" type="submit"  onclick="$.widgetAdd.nextStep();" value="下一步">
                </p>
            </form>
        </div>
    </div>
</div>

pipistrellVote/protected/admin/views/widget/add_step_3.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/widget_add.js"></script>
<?php $this->beginContent('//layouts/widget_step',array('step'=>$step));
            echo $content;
            $this->endContent(); ?>

<div id="main-content">
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;">新增挂件 → 上传显示文件</h3>
        </div>
        
        <div class="content-box-content">
            <div class="notification information png_bg">
      <div>注意上传文件格式必须为*.php<br >可一次选择多个文件同时上传</div>
    </div>
            <form id="step_1_form" onsubmit="return false;">
                 <input type="hidden" id="isUpload" value="0" />
                 <p>
                     <iframe border="no" width="100%" height="100%" src="<?php echo CHtml::normalizeUrl(array('upload/index','fname'=>'widget/views/'.Yii::app()->session['newWidgetStep'],'model'=>1)); ?>" ></iframe>
                 </p>
                <p>
                    <input class="button" type="submit"  onclick="$('#step_1_form')[0].reset();" value="重置">&nbsp;&nbsp;<input class="button" type="submit"  onclick="$.widgetAdd.finish();" value="完成">
                </p>
            </form>
        </div>
    </div>
</div>

pipistrellVote/protected/admin/views/widget/widgetEdit.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/widget.js"></script>
<div id="main-content">
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;"><?php echo $title; ?></h3>
        </div>
        <div class="content-box-content">
            <form onsubmit="return false;">
            <fieldset>
        <p>
              <label>挂件名称:</label>
                  <input class="text-input small-input" type="text" id="widgetName" value="<?php echo $data->widgetName; ?>" name="small-input" readonly="readonly">
                  <span class="input-notification success png_bg">挂件名称不可修改</span>
              
        </p>
        <p>
              <label>挂件中文名称:</label><input class="text-input small-input" type="text" id="widgetNameCn" value="<?php echo $data->widgetNameCn; ?>" name="small-input">
              
        </p>
        <p>
              <label>挂件文件名:</label>
              <input class="text-input small-input" type="text" id="widgetFile" value="<?php echo $data->widgetFile; ?>" name="small-input"><br />
              <span class="input-notification attention png_bg">如有挂件内页则依据此文件名查找，如：product.php(产品列表) productViews.php(产品详情)</span>
        </p>
        <p>
            <label>是否支持移动端：</label>
              <input type="radio" name="ismobile" value ="1" <?php if($data->ismobile):echo 'checked="checked" ';endif; ?>>
              是
              <input type="radio" name="ismobile" value ="0" <?php if(!$data->ismobile):echo 'checked="checked" ';endif; ?>>
              否
        </p>
        <p>
            <label>是否启用：</label>
              <input type="radio" name="enable" value ="1" <?php if($data->enable):echo 'checked="checked" ';endif; ?>>
              是
              <input type="radio" name="enable" value ="0" <?php if(!$data->enable):echo 'checked="checked" ';endif; ?>>
              否
        </p>
        <p>
            <label>挂件描述：</label>
            <textarea class="text-input textarea" id="description" name="textfield"  rows="5" style="display: block;"><?php echo $data->description; ?></textarea>
        </p>
        <p >
              <input class="button" type="submit" onclick="$.widget.widgetEdit('<?php echo CHtml::normalizeUrl(array("widget/putedit")); ?>','<?php echo $data->wid;?>');" value="修改">&nbsp;&nbsp;&nbsp;&nbsp;
              <input class="button" type="submit" onclick="$.uploadOpen('<?php echo CHtml::normalizeUrl(array("upload/index",'fname'=>'widget/views/'.$data->widgetName)); ?>');" value="上传模板文件"> <br ><br >
              <span class="input-notification attention png_bg">上传文件必须为.php文件  *命名必须为英文</span><br >
              <span class="input-notification attention png_bg">上传时需注意文件命名如：product.php(产品列表) productViews.php(产品详情)</span>
            </p>
            </fieldset>
            </form>
        </div>
    </div>
</div>

pipistrellVote/protected/admin/views/widget/widgetShow.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/widget.js"></script>
<div id="main-content">
    <ul class="shortcut-buttons-set">
        <li><a class="shortcut-button" href="<?php echo CHtml::normalizeUrl(array('widget/add','step'=>1)); ?>"><span> <img src="<?php echo ASSETS; ?>resources/images/icons/pencil_48.png" alt="icon"><br>
                    新增挂件</span></a></li>
    </ul>
    <div class="clear"></div>
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;">挂件管理</h3>
        </div>

        <div class="content-box-content">
            <div class="tab-content default-tab" style="display: block;">
                <table>
                    <thead>
                        <tr>
                            
                            <th>序号</th>
                            <th>名称</th>
                            <th>中文名称</th>
                            <th>默认文件</th>
                            <th>是否启用</th>
                            <th>是否支持移动</th>
                            <th>系统挂件</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="6">
                                <div class="bulk-actions align-left">

                                    <div class="pagination"><?php if($this->totalPage > 1): ?> <a href="<?php echo CHtml::normalizeUrl(array('widget/index', 'isSmallType' => $this->isSmallType, 'page' => 1)); ?>" title="首页">« 首页</a>
                                        <a href="<?php echo CHtml::normalizeUrl(array('widget/index', 'isSmallType' => $this->isSmallType, 'page' => ($this->page - 1))); ?>" title="上一页">« 上一页</a> 
                                        <?php for ($i = 1; $i <= $this->totalPage; $i++): ?>
                                            <a href="<?php echo CHtml::normalizeUrl(array('widget/index', 'isSmallType' => $this->isSmallType, 'page' => $i)); ?>" class="number <?php if($i==$this->page)echo 'current'; ?>" title="第<?php echo $i; ?>页"><?php echo $i; ?></a> 
                                        <?php endfor; ?>
                                        <a href="<?php echo CHtml::normalizeUrl(array('widget/index', 'isSmallType' => $this->isSmallType, 'page' => ($this->page + 1))); ?>" title="下一页">下一页 »</a>
                                        <a href="<?php echo CHtml::normalizeUrl(array('widget/index', 'isSmallType' => $this->isSmallType, 'page' => $this->totalPage)); ?>" title="尾页">尾页 »</a> 
                                        跳转至 <select onchange="window.location.href='<?php echo CHtml::normalizeUrl(array('widget/index', 'isSmallType' => $this->isSmallType)); ?>&page='+this.value;">
                                            <?php for ($i = 1; $i <= $this->totalPage; $i++): ?>
                                            <option <?php if($this->page == $i) echo 'selected="selected"'; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                            <?php endfor; ?>
                                        </select>

                                        共有 <?php echo $this->total; ?> 条记录
                                    <?php else: echo '共有 '.$this->total.' 条记录';endif; ?></div>
                                    
                                    <div class="clear"></div>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody id="widgetContent">
                        <?php if (is_array($data) && !empty($data)):
                            foreach ($data as $key => $value):
                                ?>
                                <tr <?php if ($key % 2 == 0) echo 'class="alt-row"'; ?>>
                                   
                                    <td><?php echo $value['wid']; ?></td>
                                    <td><?php echo $value['widgetName']; ?></td>
                                    <td><a href="<?php echo CHtml::normalizeUrl(array('widget/sqldetail','wid'=>$value['wid'])); ?>"><?php echo $value['widgetNameCn'];?></a></td>
                                    <td><?php echo $value['widgetFile']; ?> / <?php echo $value['widgetFile'].'View'; ?></td>
                                    <td><?php if ($value['enable']):echo '是';
                        else: echo '否';
                        endif; ?></td>
                                    <td><?php if ($value['ismobile']):echo '是';
                        else: echo '否';
                        endif; ?></td>
                                    <td><?php if ($value['isSys']):echo '是';
                        else: echo '否';
                        endif; ?></td>
                                    <td>

                                        <a href="<?php echo CHtml::normalizeUrl(array('widget/edit','wid'=>$value['wid'])); ?>" title="Edit"><img src="<?php echo ASSETS; ?>resources/images/icons/pencil.png" alt="修改"></a> 
                                        <a href="#" onclick="$.widget.deleteSome('<?php echo $value['wid']; ?>','1');" title="Delete"><img src="<?php echo ASSETS; ?>resources/images/icons/cross.png" alt="删除"></a> 
                                    </td>
                                </tr>
    <?php endforeach;
endif; ?>
                    </tbody>
                </table>  
            </div>

        </div>
    </div>
</div>