pipistrellVote/protected/admin/controllers/ChannelController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class ChannelController extends CController {
   public $isType = 0;
   public $isSmallType = 0;
   public $layout='application.admin.views.layouts.main';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter'
            )
        );
    }

    public function actionIndex() {
        $this->isType = 4;
        $this->isSmallType = $_GET['isSmallType'];
        $this->render('index',array(
            'data'=>$this->_getData()
        ));
    }

    private function _getData(){
        $where = adminSys::_whereWork($_POST);
        $sql = 'select id,typename,typenameEN,display,ordering,pid,ismobile from {{channel}} '.$where.' order by ordering asc ';
        $data = Yii::app()->db->createCommand($sql)->queryAll();
        if(is_array($data)){
            $bak = array('top'=>array(),'small'=>array());
            foreach ($data as $value){
                if($value['pid'] == 0){
                    $bak['top'][] = $value;
                }else{
                    $bak['small'][$value['pid']][] = $value;
                }
            }
        }
        return $bak;
    }
    
   public function actionOrderingUp(){
      
       if(empty($_POST['strOrder']))return;
           $data = explode(',', $_POST['strOrder']);
            foreach($data as $key=>$value){
                Channel::model()->updateByPk($value, array(
                    'ordering'=>(int)$_POST['ordering'][$key]
                ));
            }
        echo '<script>parent.reback("操作成功！");</script>';
   }
   public function actionChangeAtr(){
      $bak = Channel::model()->updateByPk($_POST['pkid'],array(
           $_POST['atr']=>$_POST['val']
       ));
      echo $bak;
   }
   public function actionEdit(){
       if(empty($_GET['id'])){
           $this->actionIndex ();return;
       }
       $path = Yii::app()->basePath.'/../themes/defalut/views/ins/';
       $commonArr = '';
       if(is_dir($path)){
           $commonArr = scandir($path);
       }
       $this->render('channelEdit',array(
           'data'=>Channel::model()->findByPk($_GET['id']),
           'widget'=>Widget::model()->findAll(array(
               'condition'=>' enable = :_enable ',
               'params'=>array(':_enable'=>1)
           )),
           'topData'=>Channel::model()->findAll(),
           'commonArr'=>$commonArr
       ));
   }
   public function actionDeleteCover(){
       $filetemp = dirname(Yii::app()->getBasePath()).$_POST['path'];
       if(is_file($filetemp))unlink ($filetemp);
   }
   public function actionEditData(){
       if(!IS_POST){$this->redirect (array('site/array','msg'=>'参数错误！'));return;}
       $channel = Channel::model()->findByPk($_POST['channelId']);
       
       if($channel->typename != $_POST['typename'])$channel->typename = $_POST['typename'];
       if($channel->typenameEN != $_POST['typenameEN'])$channel->typenameEN = $_POST['typenameEN'];
       if($channel->wid != $_POST['wid'])$channel->wid = $_POST['wid'];
       if($channel->widget != $_POST['tempName'])$channel->widget = $_POST['tempName'];
       if($channel->ordering != $_POST['ordering'])$channel->ordering = $_POST['ordering'];
       if($channel->keywords != $_POST['keywords'])$channel->keywords = $_POST['keywords'];
       if($channel->description != $_POST['description'])$channel->description = $_POST['description'];
       if($channel->ismobile != $_POST['ismobile'])$channel->ismobile = $_POST['ismobile'];
       if($channel->display != $_POST['display'])$channel->display = $_POST['display'];
       if($channel->pid != $_POST['topId'])$channel->pid = $_POST['topId'];
       if($channel->temp != $_POST['temp'])$channel->temp = $_POST['temp'];
       if($channel->comtemp != $_POST['comtemp'])$channel->comtemp = $_POST['comtemp'];
       if($channel->Cover != $_POST['coverin'])$channel->Cover = $_POST['coverin'];
       if($channel->smallCover != $_POST['smallcoverin'])$channel->smallCover = $_POST['smallcoverin'];
       if($channel->content != $_POST['article_content'])$channel->content = $_POST['article_content'];
       if($channel->Ctemp != $_POST['commonTemp'])$channel->Ctemp = $_POST['commonTemp'];
       if($channel->Submission != $_POST['submission'])$channel->Submission = $_POST['submission'];
       echo $channel->update();
   }
   public function actionAdd(){
       $path = Yii::app()->basePath.'/../themes/defalut/views/ins/';
       $commonArr = '';
       if(is_dir($path)){
           $commonArr = scandir($path);
       }
       $this->render('addChannel',array(
            'filetemp'=>time('Ymd'),
           'pid'=>isset($_GET['pid'])?(int)$_GET['pid']:0,
            'widget'=>Widget::model()->findAll(array(
               'condition'=>' enable = :_enable ',
               'params'=>array(':_enable'=>1)
               
           )),
           'topData'=>Channel::model()->findAll(),
            'commonArr'=>$commonArr
       ));
   }
   public function actionAdddata(){
       $channel = new Channel();
       $channel->wid = $_POST['wid'];
       $channel->ordering = $_POST['ordering'];
       $channel->typename = $_POST['typename'];
       $channel->typenameEN = $_POST['typenameEN'];
       $channel->keywords = $_POST['keywords'];
       $channel->description = $_POST['description'];
       $channel->ismobile = $_POST['ismobile'];
       $channel->display = $_POST['display'];
       $channel->pid = $_POST['topId'];
       $channel->widget = $_POST['tempName'];
       $channel->temp = $_POST['temp'];
       $channel->comtemp = $_POST['comtemp'];
       $channel->Cover = $_POST['coverin'];
       $channel->smallCover = $_POST['smallcoverin'];
       $channel->content = $_POST['article_content'];
       $channel->filetemp = $_POST['filetemp'];
       $channel->Ctemp = $_POST['commonTemp'];
       $channel->Submission = $_POST['submission'];
       echo $channel->save();
   }
   public function actionDeleteOne(){
       if(!IS_POST)$this->redirect (array('site/error','msg'=>'参数错误！'));
       $channel = Channel::model()->findByPk($_POST['pkid']);
       $path = dirname(Yii::app()->getBasePath()).'/upload/'.$channel->filetemp.'/';
       if(is_file($path.$channel->Cover))unlink($path.$channel->Cover);
       if(is_file($path.$channel->smallCover))unlink($path.$channel->smallCover);
       echo $channel->delete();
   }
}

?>

pipistrellVote/protected/admin/controllers/ListArtController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class ListArtController extends CController {
    public $row = 10;
    public $page = 1;
    public $total = 0;
    public $ordering = 'asc';
    public $isType = 0;
    public $isSmallType = 0;
    public $totalPage = 0;
    public $layout='application.admin.views.layouts.main';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter'
            )
        );
    }

    public function actionIndex(){

        if(isset($_GET['row']) && !empty($_GET['row'])){
            $this->row = $_GET['row'];
            unset($_GET['row']);
        }
        if(isset($_GET['page'])&&!empty($_GET['page'])){
            $this->page = $_GET['page'];
            unset($_GET['page']);
        }
        if(isset($_GET['ordering']) && !empty($_GET['ordering'])){
            $this->ordering = $_GET['ordering'];
            unset($_GET['ordering']);
        }
        $this->isType = 5;
        $this->isSmallType = $_GET['isSmallType'];
        $_GET['arcrank'] = 1;
        $where = adminSys::_whereWork($_GET);
        $limit = ' limit '.($this->page-1)*$this->row.','.$this->row;
        $this->render('index',array(
            'data'=>$this->_getData($where,$limit),
            'channel'=>Channel::model()->findByPk($_GET['artTopId'])
        ));
    }
    public function actionMemberSet(){
        if(isset($_GET['row']) && !empty($_GET['row'])){
            $this->row = $_GET['row'];
            unset($_GET['row']);
        }
        if(isset($_GET['page'])&&!empty($_GET['page'])){
            $this->page = $_GET['page'];
            unset($_GET['page']);
        }
        if(isset($_GET['ordering']) && !empty($_GET['ordering'])){
            $this->ordering = $_GET['ordering'];
            unset($_GET['ordering']);
        }
        $this->isType = 4;
        $this->isSmallType = $_GET['isSmallType'];
        $_GET['midn'] = 1;
        $channelId = empty($_GET['channelid'])?'':$_GET['channelid'];
        $where = adminSys::_whereWork($_GET,'a.');
        $limit = ' limit '.($this->page-1)*$this->row.','.$this->row;
        $this->render('memberSet',array(
            'data'=>$this->_getMemData($where,$limit),
            'channel'=>Channel::model()->findAllByAttributes(array('Submission'=>1)),
            'channelId'=>$channelId
        ));
    }
    private function _getMemData($where,$limit=''){
        $sql = 'select a.*,c.typename from {{article}} as a '.
                'left join {{channel}} as c on a.channelId = c.id '.$where.' order by a.ordering '.$this->ordering.' '.$limit;
        $sql1 = 'select count(*) as count_num from {{article}} as a '.$where;
        $data = Yii::app()->db->createCommand($sql)->queryAll();
        $data1 = Yii::app()->db->createCommand($sql1)->queryRow();
        $this->total = $data1['count_num'];
        $this->totalPage = ceil($this->total/$this->row);
        return $data;
    }
    private function _getData($where,$limit=''){
        $sql = 'select * from {{article}} '.$where.' order by ordering '.$this->ordering.' '.$limit;
        $sql1 = 'select count(*) as count_num from {{article}} '.$where;
        $data = Yii::app()->db->createCommand($sql)->queryAll();
        $data1 = Yii::app()->db->createCommand($sql1)->queryRow();
        $this->total = $data1['count_num'];
        $this->totalPage = ceil($this->total/$this->row);
        return $data;
    }
     public function actionOrderingUp(){
      
       if(empty($_POST['strOrder']))return;
           $data = explode(',', $_POST['strOrder']);
            foreach($data as $key=>$value){
                Article::model()->updateByPk($value, array(
                    'ordering'=>(int)$_POST['ordering'][$key]
                ));
            }
        echo '<script>parent.reback(1);</script>';
   }
   public function actionEdit(){
       if(!isset($_GET['pkid'])||empty($_GET['pkid']))$this->redirect(array('listart/index'));
       
       $widget = Widget::model()->findByPk($_GET['wid']);
       if(empty($widget))$this->redirect(array('listart/index'));
       $addfileds = require_once 'addfileds_'.$widget->tableName.'.php';  
       $addCN = require_once 'addfiledsCn_'.$widget->tableName.'.php';
       $this->isSmallType = $_GET['channelId'];
       if(!empty($widget->Attribute)){
           $attributeArr = explode(',', $widget->Attribute);
           if(count($attributeArr) > 1){
               $attribute = '';
               foreach($attributeArr as $value){
                   $attribute .= ',';
                   $attribute .= 'd.'.$value;
               }
           }else{
               $attribute = ',d.'.$attributeArr[0];
           }
       }
       $sql = 'select a.id,a.channelId,a.title,a.keywords,a.description,a.click,a.Slitpic,a.litpic,a.flag,a.sourceURL,a.source,a.Awrite,a.senddate,a.ismobile,a.ordering,a.filetemp'.$attribute.' from {{article}} as a '.
           'left join {{add'.$widget->tableName.'}} as d on a.id = d.id where a.id = "'.$_GET['pkid'].'" ';
       $data = Yii::app()->db->createCommand($sql)->queryRow();
       $this->render('edit',array(
           'data'=>$data,
           'channel'=>Channel::model()->find('wid=:_wid',array(
               ':_wid'=>$widget->wid
           )),
           'attribute'=>$attributeArr,
           'addfileds'=>$addfileds,
           'modelName'=>$widget->tableName,
           'addCN'=>$addCN
       ));
   }
   public function actionAdd(){
       if(!isset($_GET['wid'])||empty($_GET['wid']))$this->redirect(array('listart/index'));
       $widget = Widget::model()->findByPk($_GET['wid']);
       if(!empty($widget->Attribute)){
           $attributeArr = explode(',', $widget->Attribute);

       }
       $this->isSmallType = $_GET['channelId'];
       $addfileds = require_once 'addfileds_'.$widget->tableName.'.php';  
       $addCN = require_once 'addfiledsCn_'.$widget->tableName.'.php';
        $this->render('add',array(
           'channelId'=>$_GET['channelId'],
            'wid'=>$_GET['wid'],
           'attribute'=>$attributeArr,
           'addfileds'=>$addfileds,
           'modelName'=>$widget->tableName,
           'addCN'=>$addCN,
           'filetemp'=>date('Ymd')
       ));
   }
   public function actionEditsave(){
       if(!IS_POST||!isset($_POST['pkid']))$this->redirect (array('listart/index'));
       if(empty($_POST['title'])){
           echo '<script>parent.showBack("标题不能为空！");</script>';
           return;
       }
       
       if($_POST['pkid']){
       $article = Article::model()->findByPk($_POST['pkid']);
       $add = "\$obj = Add".$_POST['modelName']."::model()->findByPk(".$_POST['pkid'].");";
       $article->Aupdate = time()-(8*3600);
       eval($add);
       }else{
           if(empty($_POST['wid']) || empty($_POST['channelId']) || empty($_POST['filetemp']))$this->redirect (array('site/error','msg'=>'参数错误，请与管理员联系！'));
           $article = new Article();
           $add = "\$obj = new Add".$_POST['modelName']."();";
           $article->senddate = time()-(8*3600);
           $article->wid = $_POST['wid'];
           $article->channelId = $_POST['channelId'];
           $article->channelIdAll = adminSys::_getAllId($_POST['channelId']);
           $article->filetemp = $_POST['filetemp'];
           $article->Awrite = $_POST['awrite'];
           $article->save();
           eval($add);
           $obj->id = $article->id;
           $obj->channelId = $article->channelId;
           $obj->userip = $_SERVER["REMOTE_ADDR"];
           $obj->save();
       }
       $addfileds = require_once 'addfileds_'.$_POST['modelName'].'.php';  
       if(!empty($_POST['title']) && $_POST['title'] != $article->title)$article->title = $_POST['title'];
       if($_POST['keywords'] != $article->keywords)$article->keywords = $_POST['keywords'];
       if(!empty($_POST['description']) && $_POST['description'] != $article->description)$article->description = $_POST['description'];
       if(!empty($_POST['ordering']) && $_POST['ordering'] != $article->ordering)$article->ordering = $_POST['ordering'];
       if(!empty($_POST['source']) && $_POST['source'] != $article->source)$article->source = $_POST['source'];
       if(!empty($_POST['sourceURL']) && $_POST['sourceURL'] != $article->sourceURL)$article->sourceURL = $_POST['sourceURL'];
       if(!empty($_POST['Awrite']) && $_POST['Awrite'] != $article->Awrite)$article->Awrite = $_POST['Awrite'];
       if($_POST['ismobile'] != 'undefined' && $_POST['ismobile'] != $article->ismobile)$article->ismobile = $_POST['ismobile'];
       if(!empty($_POST['flag']) && $_POST['flag'] != $article->flag)$article->flag = $_POST['flag'];
       if(!empty($_POST['litpic']) && $_POST['litpic'] != $article->litpic)$article->litpic = $_POST['litpic'];
       if(!empty($_POST['Slitpic']) && $_POST['Slitpic'] != $article->Slitpic)$article->Slitpic = $_POST['Slitpic'];
       if(isset($_POST['spicalModel']) && !empty($_POST['spicalModel'])){
        eval("\$this->_Edit".$_POST['spicalModel']."(&\$obj,\$addfileds);");   
       }else{
       foreach($addfileds as $key=>$value){
           if($value == 'date'){
           $obj->$key = adminSys::_time($_POST[$key], 2);   
           }else{
           $obj->$key = isset($_POST[$key])?$_POST[$key]:null;
           }
       }
       }
       if($_POST['modelName']=='vote'){
           $voteCount = 0;
           if(!empty($_POST['voteName'])){
               foreach($_POST['voteName'] as $k=>$v){
                   $lock = true;
                   if(empty($_POST['voteid'][$k])){
                   $vote = new Addvote_infos();
                   $vote->aid = $article->id;
                   $vote->count = 0;
                   $lock=false;
                   }else{
                       $vote = Addvote_infos::model()->findByPk($_POST['voteid'][$k]);
                   }
                   $vote->votename = $v;
                   $vote->litpic = $_POST['voteLitpic'][$k];

pipistrellVote/protected/admin/controllers/VoteController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class VoteController extends CController {
public $isType = 0;
   public $isSmallType = 0;
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter'
            )
        );
    }

    public function actionShow() {
        $this->layout='application.admin.views.layouts.main';
        $this->isType = 1;
        $this->isSmallType = $_GET['isSmallType'];
        $a = Addvote::model()->findByPk($_GET['pkid']);
        $data = Addvote_infos::model()->findAll(' aid=:aid ',array(':aid'=>$_GET['pkid']));
        $this->render('showVote',array(
            'a'=>$a,
            'data'=>$data,
            'title'=>$_GET['title']
        ));
    }

}

?>

pipistrellVote/protected/admin/views/listart/index.php
<script type="text/javascript" src="<?php echo ASSETS;?>js/listart.js"></script>
<div id="main-content">

    <div class="clear"></div>
    <div class="content-box">
        <div class="content-box-header">
            <h3 style="cursor: s-resize;"><a href="/">首页</a>&nbsp;>>&nbsp;<a href="<?php echo CHtml::normalizeUrl(array('channel/index','isSmallType'=>1)); ?>">栏目管理</a>&nbsp;>>&nbsp;<?php echo $channel->typename; ?>&nbsp;>>&nbsp;内容管理</h3>
            <input class="button" style="float:right; margin-top: 7px; margin-right: 15px;" type="submit" onclick="$.listart.updateOrd();" value="更新排序">
        </div>
    
        <div class="content-box-content">
            <ul class="shortcut-buttons-set">
                <li><a class="shortcut-button" href="<?php echo CHtml::normalizeUrl(array('listart/add', 'wid' => $channel->wid, 'channelId' => $channel->id)); ?>"><span> <img src="<?php echo ASSETS; ?>resources/images/icons/pencil_48.png" alt="icon"><br>
                            新增内容</span></a></li>

                <li><a class="shortcut-button" href="javascript:void(0);" onclick="$.listart.deleteAll();"><span> <img src="<?php echo ASSETS; ?>resources/images/icons/paper_content_pencil_48.png" alt="icon"><br>
                            批量删除内容</span></a></li>

    </ul>
    <div class="clear"></div>
            <div class="tab-content default-tab" style="display: block;">
                <table>
                    <thead>
                        <tr>
                            <th><input class="check-all" type="checkbox"></th>
                            <th>序号</th>
                            <th>名称</th>
                            <th>状态</th>
                            <th>属性</th>
                            <th>作者</th>
                            <th>是否支持移动</th>
                            <th>提交时间</th>
                            <th>操作</th>
                            <th>排序</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="6">
                                <div class="bulk-actions align-left">

                                    <div class="pagination">
                                        <?php if($this->totalPage > 1): ?><a href="<?php echo CHtml::normalizeUrl(array('listart/index', 'isSmallType' => $this->isSmallType, 'page' => 1)); ?>" title="首页">« 首页</a>
                                        <a href="<?php echo CHtml::normalizeUrl(array('listart/index', 'isSmallType' => $this->isSmallType, 'page' => ($this->page - 1))); ?>" title="上一页">« 上一页</a> 
                                        <?php for ($i = 1; $i <= $this->totalPage; $i++): ?>
                                            <a href="<?php echo CHtml::normalizeUrl(array('listart/index', 'isSmallType' => $this->isSmallType, 'page' => $i)); ?>" class="number <?php if($i==$this->page)echo 'current'; ?>" title="第<?php echo $i; ?>页"><?php echo $i; ?></a> 
                                        <?php endfor; ?>
                                        <a href="<?php echo CHtml::normalizeUrl(array('listart/index', 'isSmallType' => $this->isSmallType, 'page' => ($this->page + 1))); ?>" title="下一页">下一页 »</a>
                                        <a href="<?php echo CHtml::normalizeUrl(array('listart/index', 'isSmallType' => $this->isSmallType, 'page' => $this->totalPage)); ?>" title="尾页">尾页 »</a> 
                                        跳转至 <select onchange="window.location.href='<?php echo CHtml::normalizeUrl(array('listart/index', 'isSmallType' => $this->isSmallType)); ?>&page='+this.value;">
                                            <?php for ($i = 1; $i <= $this->totalPage; $i++): ?>
                                            <option <?php if($this->page == $i) echo 'selected="selected"'; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                            <?php endfor; ?>
                                        </select>

                                        共有 <?php echo $this->total; ?> 条记录
                                    <?php else: echo '共有 '.$this->total.' 条记录';endif; ?></div>
                                    <div class="clear"></div>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody id="widgetContent">
                    <form  action="<?php echo CHtml::normalizeUrl(array('listart/orderingUp')); ?>" method="post"  id="orderingForm" target="hiddenFr"> 
                        <?php if (is_array($data) && !empty($data)):
                            foreach ($data as $key => $value):
                                ?>
                                <tr <?php if ($key % 2 == 0) echo 'class="alt-row"'; ?> id="<?php echo $value['id']; ?>">
                                   <td><input type="checkbox" value="<?php echo $value['id'].','.$value['wid']; ?>" name="checkAll"></td>
                                    <td><?php echo $value['id']; ?></td>
                                    <td><a href="<?php echo CHtml::normalizeUrl(array('listart/edit','pkid'=>$value['id'],'wid'=>$value['wid'],'channelId'=>$value['channelId'])); ?>"><?php echo adminSys::_cutStr($value['title'],6); ?></a></td>
                                    <td><?php echo adminSys::_arcrankCN($value['arcrank']); ?></td>
                                    <td><?php echo adminSys::_flagCN($value['flag']); ?></td>
                                    <td><?php echo $value['Awrite'];?></td>
                                    <td>
                                        <?php if ($value['enable']):echo '是';
                        else: echo '否';
                        endif; ?></td>
                                    <td><?php echo adminSys::_time($value['senddate'],1); ?>
                                    </td>
                                    <td>
                                        
                                        <a href="<?php echo CHtml::normalizeUrl(array('listart/edit','pkid'=>$value['id'],'wid'=>$value['wid'],'channelId'=>$value['channelId'])); ?>" title="修改"><img src="<?php echo ASSETS; ?>resources/images/icons/pencil.png" alt="修改"></a> 
                                        <a href="#" onclick="$.listart.deleteOne('<?php echo $value['id']; ?>','<?php echo $channel->wid; ?>');" title="删除"><img src="<?php echo ASSETS; ?>resources/images/icons/cross.png" alt="删除"></a> 
                                        <a href="info<?php echo $value['id'].'.'.$value['channelId']; ?>.html" target="_BLANK"  title="预览PC"><img src="<?php echo ASSETS; ?>resources/images/icons/webview.png" alt="预览PC"></a> 
                                        <?php if($channel->wid=='26'): ?>
                                        <a href="<?php echo CHtml::normalizeUrl(array('vote/show','pkid'=>$value['id'],'title'=>$value['title'])); ?>" ><img src="<?php echo ASSETS; ?>resources/images/icons/information.png" alt="查看投票情况" /></a>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <input type="number" value="<?php echo $value['ordering']; ?>" name="ordering[]" style="height:18px; margin: 0px; padding:0px; width:30px; text-align: center;" />
                                    </td>
                                </tr>
    <?php endforeach;
endif; ?>
                                <input type="hidden" id="strOrder" name="strOrder" />
                    </form>
                    </tbody>
                </table>  
                <iframe name="hiddenFr" style="display: none;" border="no" ></iframe>
            </div>

        </div>
    </div>
</div>
    <script type="text/javascript">
    function reback(msg){
        if(msg == 1){
            $.showMsg('<div class="notification success png_bg"><div>操作成功！系统将在<i id="scerdShow">2</i>秒后返回栏目管理</div></div>');
                    var i = 2;
                    window.setInterval(function(){
                        if(i > 1){
                            i--;
                            $('#scerdShow').html(i);
                            return;
                        }
                        window.location.reload();
                    },1000); 
        }
    }
    </script>