pipistrellVote/protected/admin/controllers/ChannelController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class ChannelController extends CController {
   public $isType = 0;
   public $isSmallType = 0;
   public $layout='application.admin.views.layouts.main';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter'
            )
        );
    }

    public function actionIndex() {
        $this->isType = 4;
        $this->isSmallType = $_GET['isSmallType'];
        $this->render('index',array(
            'data'=>$this->_getData()
        ));
    }

    private function _getData(){
        $where = adminSys::_whereWork($_POST);
        $sql = 'select id,typename,typenameEN,display,ordering,pid,ismobile from {{channel}} '.$where.' order by ordering asc ';
        $data = Yii::app()->db->createCommand($sql)->queryAll();
        if(is_array($data)){
            $bak = array('top'=>array(),'small'=>array());
            foreach ($data as $value){
                if($value['pid'] == 0){
                    $bak['top'][] = $value;
                }else{
                    $bak['small'][$value['pid']][] = $value;
                }
            }
        }
        return $bak;
    }
    
   public function actionOrderingUp(){
      
       if(empty($_POST['strOrder']))return;
           $data = explode(',', $_POST['strOrder']);
            foreach($data as $key=>$value){
                Channel::model()->updateByPk($value, array(
                    'ordering'=>(int)$_POST['ordering'][$key]
                ));
            }
        echo '<script>parent.reback("操作成功！");</script>';
   }
   public function actionChangeAtr(){
      $bak = Channel::model()->updateByPk($_POST['pkid'],array(
           $_POST['atr']=>$_POST['val']
       ));
      echo $bak;
   }
   public function actionEdit(){
       if(empty($_GET['id'])){
           $this->actionIndex ();return;
       }
       $path = Yii::app()->basePath.'/../themes/defalut/views/ins/';
       $commonArr = '';
       if(is_dir($path)){
           $commonArr = scandir($path);
       }
       $this->render('channelEdit',array(
           'data'=>Channel::model()->findByPk($_GET['id']),
           'widget'=>Widget::model()->findAll(array(
               'condition'=>' enable = :_enable ',
               'params'=>array(':_enable'=>1)
           )),
           'topData'=>Channel::model()->findAll(),
           'commonArr'=>$commonArr
       ));
   }
   public function actionDeleteCover(){
       $filetemp = dirname(Yii::app()->getBasePath()).$_POST['path'];
       if(is_file($filetemp))unlink ($filetemp);
   }
   public function actionEditData(){
       if(!IS_POST){$this->redirect (array('site/array','msg'=>'参数错误！'));return;}
       $channel = Channel::model()->findByPk($_POST['channelId']);
       
       if($channel->typename != $_POST['typename'])$channel->typename = $_POST['typename'];
       if($channel->typenameEN != $_POST['typenameEN'])$channel->typenameEN = $_POST['typenameEN'];
       if($channel->wid != $_POST['wid'])$channel->wid = $_POST['wid'];
       if($channel->widget != $_POST['tempName'])$channel->widget = $_POST['tempName'];
       if($channel->ordering != $_POST['ordering'])$channel->ordering = $_POST['ordering'];
       if($channel->keywords != $_POST['keywords'])$channel->keywords = $_POST['keywords'];
       if($channel->description != $_POST['description'])$channel->description = $_POST['description'];
       if($channel->ismobile != $_POST['ismobile'])$channel->ismobile = $_POST['ismobile'];
       if($channel->display != $_POST['display'])$channel->display = $_POST['display'];
       if($channel->pid != $_POST['topId'])$channel->pid = $_POST['topId'];
       if($channel->temp != $_POST['temp'])$channel->temp = $_POST['temp'];
       if($channel->comtemp != $_POST['comtemp'])$channel->comtemp = $_POST['comtemp'];
       if($channel->Cover != $_POST['coverin'])$channel->Cover = $_POST['coverin'];
       if($channel->smallCover != $_POST['smallcoverin'])$channel->smallCover = $_POST['smallcoverin'];
       if($channel->content != $_POST['article_content'])$channel->content = $_POST['article_content'];
       if($channel->Ctemp != $_POST['commonTemp'])$channel->Ctemp = $_POST['commonTemp'];
       if($channel->Submission != $_POST['submission'])$channel->Submission = $_POST['submission'];
       echo $channel->update();
   }
   public function actionAdd(){
       $path = Yii::app()->basePath.'/../themes/defalut/views/ins/';
       $commonArr = '';
       if(is_dir($path)){
           $commonArr = scandir($path);
       }
       $this->render('addChannel',array(
            'filetemp'=>time('Ymd'),
           'pid'=>isset($_GET['pid'])?(int)$_GET['pid']:0,
            'widget'=>Widget::model()->findAll(array(
               'condition'=>' enable = :_enable ',
               'params'=>array(':_enable'=>1)
               
           )),
           'topData'=>Channel::model()->findAll(),
            'commonArr'=>$commonArr
       ));
   }
   public function actionAdddata(){
       $channel = new Channel();
       $channel->wid = $_POST['wid'];
       $channel->ordering = $_POST['ordering'];
       $channel->typename = $_POST['typename'];
       $channel->typenameEN = $_POST['typenameEN'];
       $channel->keywords = $_POST['keywords'];
       $channel->description = $_POST['description'];
       $channel->ismobile = $_POST['ismobile'];
       $channel->display = $_POST['display'];
       $channel->pid = $_POST['topId'];
       $channel->widget = $_POST['tempName'];
       $channel->temp = $_POST['temp'];
       $channel->comtemp = $_POST['comtemp'];
       $channel->Cover = $_POST['coverin'];
       $channel->smallCover = $_POST['smallcoverin'];
       $channel->content = $_POST['article_content'];
       $channel->filetemp = $_POST['filetemp'];
       $channel->Ctemp = $_POST['commonTemp'];
       $channel->Submission = $_POST['submission'];
       echo $channel->save();
   }
   public function actionDeleteOne(){
       if(!IS_POST)$this->redirect (array('site/error','msg'=>'参数错误！'));
       $channel = Channel::model()->findByPk($_POST['pkid']);
       $path = dirname(Yii::app()->getBasePath()).'/upload/'.$channel->filetemp.'/';
       if(is_file($path.$channel->Cover))unlink($path.$channel->Cover);
       if(is_file($path.$channel->smallCover))unlink($path.$channel->smallCover);
       echo $channel->delete();
   }
}

?>

pipistrellVote/protected/admin/controllers/JurisdictionController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class JurisdictionController extends CController {
   public $isType = 0;
   public $isSmallType = 0;
   public $row = 10;
   public $page = 1;
   public $totalPage = 0;
   public $total = 0;
   
   public $row1 = 10;
   public $page1 = 1;
   public $totalPage1 = 0;
   public $total1 = 0;
   public $layout='application.admin.views.layouts.mainAD';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter'
            )
        );
    }
    
    protected function _time($time, $model = null) {
        if ($model == 1) {
            return $time - (8 * 3600); //转格林威治时间
        } else if ($model == 2) {
            return $time + (8 * 3600); //转北京时间
        }
     }
     

     public function actionIndex() {        
        $this->page = isset($_GET['page'])&&(!empty($_GET['page']))?$_GET['page']:1;
        $this->isType = 9;
        $this->isSmallType = $_GET['isSmallType'];
        $DTC_arr=array();        
        $limit = ' limit '.(($this->page-1)*$this->row).','.$this->row;
        $where = adminSys::_whereWork($_POST);
        $sql = 'select * from {{sysadmin}} '.$where.$limit;
        $sql1 = 'select count(*) as count_num from {{sysadmin}} '.$where;
        $DTC_arr = Yii::app()->db->createCommand($sql)->queryAll(); 
        $DTC_arr_count = Yii::app()->db->createCommand($sql1)->queryAll();
        $this->totalPage = ceil($DTC_arr_count[0]['count_num']/$this->row);
        $this->total = $DTC_arr_count[0]['count_num'];
        $this->render('Cmng_Ctrl',array(              //局部渲染
            'Count_arr'=>$DTC_arr,
        ));
    }
     public function actionCaddRender() {      
        $this->render('Cadd_Ctrl',array(              //局部渲染        
        )); 
    }
    
    public function actionCountInsert(){
        if(!empty($_POST)){
            $DTC = new Sysadmin();
            $DTC->groupid=(int)$_POST['groupid'];
            $DTC->user=$_POST['user'];
            $DTC->password= md5('bjt'.$_POST['password'].'cms');
            $DTC->loginip='::1';
            $DTC->uname=$_POST['uname'];
            $DTC->logintime=(int)$this->_time(time(),1);
            $DTC->email=$_POST['email'];  
            $DTC->staus=(int)$_POST['status'];
            $DTC->save();
            echo $DTC->id; 
        }
    }
    public function actionCountDelete(){
         if(isset($_POST['id'])){
             if($_POST['id']<>1){
                $count = Sysadmin::model()->deleteByPk($_POST['id']);
                echo $count;
             }else{
                 echo -1;
             }
         }  else{
             echo 0;
         }
    }
    public function actionCountRender(){
        if(!empty($_GET)){
            $tar_C = Sysadmin::model()->findByPk($_GET['id']);
            $this->render('Cmodify_Ctrl',array(
                'id'=>$_GET['id'],
                'groupid'=>$_GET['groupid'],
                'user'=>$_GET['user'],
                'uname'=>$_GET['uname'],
                'password'=>$_GET['password'],
                'email'=>$_GET['email'],
                'status'=>$_GET['status']
            )); 
        }            
    }
    public function actionTarCRender(){
        if(!empty($_POST)){
            //$tar_C = Sysadmin::model()->findByPk($_POST['id']);
            $this->render('Cmodify_Ctrl',array(  
                'groupid'=>$_POST['groupid'],
                'user'=>$_POST['user'],
                'uname'=>$_POST['uname'],
                'password'=>$_POST['password'],
                'email'=>$_POST['email'],
                'status'=>$_POST['status']
            )); 
        }            
    }
   
    public function actionCountUpdate(){
        if(!empty($_POST)){
            $tar_C = Sysadmin::model()->findByPk($_POST['id']);            
            if($tar_C->groupid != $_POST['groupid'] && !empty($_POST['groupid']) && $_POST['groupid'] != 'undefined'){$tar_C->groupid = $_POST['groupid'];}
            if($tar_C->user != $_POST['user'] && !empty($_POST['user']) && $_POST['user'] != 'undefined'){$tar_C->user = $_POST['user'];}            
            $tar_C->password = md5('bjt'.$_POST['password'].'cms');           
            if($tar_C->uname != $_POST['uname'] && !empty($_POST['uname']) && $_POST['uname'] != 'undefined'){$tar_C->uname = $_POST['uname'];}            
            if($tar_C->email != $_POST['email'] && !empty($_POST['email']) && $_POST['email'] != 'undefined'){$tar_C->email = $_POST['email'];}            
            if($tar_C->staus != $_POST['status'] && !empty($_POST['status']) && $_POST['status'] != 'undefined'){$tar_C->staus = $_POST['status'];}
            $tar_C->update();  
            $bak=$tar_C->id;            
            echo $bak;
        }        
        else{
            echo 0;
        }
    }
        
    
     public function actionCountSearch() {        
        $this->page = isset($_GET['page'])?$_GET['page']:1;
        $this->isType = 9;
        $this->isSmallType = $_GET['isSmallType'];
        $DTC_arr=array();        
        $limit = ' limit '.(($this->page-1)*$this->row).','.$this->row;
        $where = adminSys::_whereWork($_POST);
        $sql = 'select * from {{sysadmin}} '.$where.$limit;
        $sql1 = 'select count(*) as count_num from {{sysadmin}} '.$where;
        $DTC_arr = Yii::app()->db->createCommand($sql)->queryAll(); 
        $DTC_arr_count = Yii::app()->db->createCommand($sql1)->queryAll();
        $this->totalPage = ceil($DTC_arr_count[0]['count_num']/$this->row);
        $this->total = $DTC_arr_count[0]['count_num'];
        $this->render('Cmng_Ctrl',array(              //局部渲染
            'Count_arr'=>$DTC_arr,
        ));
    }
}

pipistrellVote/protected/admin/controllers/UploadController.php
<?php
/*
 * author:pipistrll
 * email:appyouxiang@163.com
 */
class UploadController extends CController {

    public $view = 'index';
    public $model = 0;
    public $domId = '';
    public function filters() {
        return array(
            array(
                'application.admin.filters.MemcheckFilter - Uploadfile'
            )
        );
    }

    public function actionIndex() {
        $this->model = isset($_GET['model']) && !empty($_GET['model']) ? $_GET['model'] : 0;
        $this->view = isset($_GET['view']) && !empty($_GET['view']) ? $_GET['view'] : 'index';
        $this->domId = isset($_GET['id']) && !empty($_GET['id'])?$_GET['id']:'';
        $this->renderPartial($this->view, array(
            'upPath' => CHtml::normalizeUrl(array('upload/uploadfile')),
            'fname' => $_GET['fname']
        ));
    }

    public function actionUploadfile() {
        
        if (!empty($_POST)) {
            $file_n = '';
            if (isset($_POST['fileName'])) {
                $file_n = $_POST['fileName'];
            } else if (isset($_GET['fileName'])) {
                $file_n = $_GET['fileName'];
            }
            $POST_MAX_SIZE = ini_get('post_max_size');
            $unit = strtoupper(substr($POST_MAX_SIZE, -1));
            $multiplier = ($unit == 'M' ? 1048576 : ($unit == 'K' ? 1024 : ($unit == 'G' ? 1073741824 : 1)));

            if ((int) $_SERVER['CONTENT_LENGTH'] > $multiplier * (int) $POST_MAX_SIZE && $POST_MAX_SIZE) {
                header("HTTP/1.1 500 Internal Server Error");
                echo "POST exceeded maximum allowed size.";
                exit(0);
            }

            $save_path = dirname(Yii::app()->getBasePath()) . "/" . $file_n . "/";
            if (!file_exists($save_path)) {
                mkdir($save_path);
            }
            $upload_name = "Filedata";
            $max_file_size_in_bytes = 2147483647;    // 2GB 
            $extension_whitelist = array("php", "gif", "jpg", "png");
            $valid_chars_regex = '.A-Z0-9_ !@#$%^&()+={}\[\]\',~`-';

            $MAX_FILENAME_LENGTH = 260;
            $file_name = "";
            $file_extension = "";
            $uploadErrors = array(
                0 => "0",
                1 => "1",
                2 => "2",
                3 => "3",
                4 => "4",
                6 => "5"
            );
          
            if (!isset($_FILES[$upload_name])) {
                $this->HandleError("No upload found in \$_FILES for " . $upload_name);
                exit(0);
            } else if (isset($_FILES[$upload_name]["error"]) && $_FILES[$upload_name]["error"] != 0) {
                $this->HandleError($uploadErrors[$_FILES[$upload_name]["error"]]);
                exit(0);
            } else if (!isset($_FILES[$upload_name]["tmp_name"]) || !@is_uploaded_file($_FILES[$upload_name]["tmp_name"])) {
                $this->HandleError("Upload failed is_uploaded_file test.");
                exit(0);
            } else if (!isset($_FILES[$upload_name]['name'])) {
                $this->HandleError("File has no name.");
                exit(0);
            }

            $file_size = @filesize($_FILES[$upload_name]["tmp_name"]);
            if (!$file_size || $file_size > $max_file_size_in_bytes) {
                $this->HandleError("File exceeds the maximum allowed size");
                exit(0);
            }

            if ($file_size <= 0) {
                $this->HandleError("File size outside allowed lower bound");
                exit(0);
            }

            $file_name = preg_replace('/[^' . $valid_chars_regex . ']|\.+$/i', "", basename($_FILES[$upload_name]['name']));
            if (strlen($file_name) == 0 || strlen($file_name) > $MAX_FILENAME_LENGTH) {
                $this->HandleError("Invalid file name");
                exit(0);
            }
            
            $path_info = pathinfo($_FILES[$upload_name]['name']);
            $file_extension = $path_info["extension"];
            $is_valid_extension = false;
            foreach ($extension_whitelist as $extension) {
                if (strcasecmp($file_extension, $extension) == 0) {
                    $is_valid_extension = true;
                    break;
                }
            }

            if (!$is_valid_extension) {
                $this->HandleError("1444");
                exit(0);
            }

            $file_name = date("YmdHis").'_'.rand(10000, 99999).'.'.$path_info["extension"];
            if (!@move_uploaded_file($_FILES[$upload_name]["tmp_name"], $save_path . $file_name)) {
                $this->HandleError("文件无法保存");
                exit(0);
            }

            echo $file_name;
            return;
        }
    }

 

}

?>

pipistrellVote/protected/admin/views/layouts/Advert_step.php
<link rel="stylesheet" href="<?php echo ASSETS;?>css/widget_step.css" type="text/css" />
<div class="stepInfo">

	<ul>
            <li id="w_brg1"></li>
            <li id="w_brg2"></li>
	</ul>
	
    <div id="w_s1" class="stepIco stepIco1">1
		<div class="stepText">基本设置</div>
	</div>
	
    <div id="w_s2" class="stepIco stepIco2">2
		<div class="stepText">上传广告图片</div>
	</div>
	
    <div id="w_s3" class="stepIco stepIco3">3
		<div class="stepText">完成</div>
	</div>
	
</div>
<br >
<div class="clear"></div>

pipistrellVote/protected/admin/views/layouts/addvote.php
<style>
    .voteBox { width:98%; height:auto; margin:0 auto;}
    .voteBox li { width:200px; height:auto; float:left; display: inline;}
    .voteBox li a { width:60%; height:15px; line-height:15px; display: block; text-align: center; }
</style>

<script type="text/javascript" src="<?php echo ASSETS; ?>/js/addvote.js" ></script>
<p class="config">
    <a class="button" href="javascript:void(0);" onclick="$.vote.addOption('<?php echo CHtml::normalizeUrl(array('upload/index', 'fname' => '/upload/' . $filetemp, 'model' => 6)) ?>','<?php echo ASSETS . 'base/NOIMG.jpg'; ?>');">增加投票项</a>
</p>
<div  >
    <ul class="voteBox" id="voteBox">
        <li>
            <label>标题</label><input class="text-input larger-input" type="text" name="voteName[]" />
            <img id="vlitS1" class="coverImg" style="margin-top:5px; margin-bottom: 5px;" src="<?php echo ASSETS . 'base/NOIMG.jpg'; ?>" />
            <input type="hidden" name="voteid[]" value="0" />
            <input type="hidden" name="voteCount[]" value="0" />
            <input type="hidden" name="voteLitpic[]" id="vlit1" />
            <iframe border="no" width="100%" height="60px" src="<?php echo CHtml::normalizeUrl(array('upload/index', 'fname' => '/upload/' . $filetemp,'id'=>'1', 'model' => 6)) ?>" ></iframe>
        </li>
    </ul>
            
</div>
<script type="text/javascript">
function voteLitpic(id,litpic){
         var old = $('#vlit'+id).val();
         
         var path = '/upload/<?php echo $filetemp; ?>/';
         if(old!=''){
         $.ajax({
             type:'post',
             data:'path='+path+old,
             url:'<?php echo CHtml::normalizeUrl(array('channel/deleteCover')); ?>'
         });
         }
         path = path+litpic;
         $('#vlitS'+id).attr('src',path);
         $('#vlit'+id).val(litpic);
}
</script>

pipistrellVote/protected/admin/views/layouts/editvote.php
<style>
    .voteBox { width:98%; height:auto; margin:0 auto;}
    .voteBox li { width:200px; height:auto; float:left; display: inline;}
    .voteBox li a { width:60%; height:15px; line-height:15px; display: block; text-align: center; }
</style>
<?php $data = Addvote_infos::model()->findAll(' aid=:aid ',array(':aid'=>$aid)); ?>
<script type="text/javascript" src="<?php echo ASSETS; ?>/js/addvote.js" ></script>
<p class="config">
    <a class="button" href="javascript:void(0);" onclick="$.vote.addOption('<?php echo CHtml::normalizeUrl(array('upload/index', 'fname' => '/upload/' . $filetemp, 'model' => 6)) ?>','<?php echo ASSETS . 'base/NOIMG.jpg'; ?>');">增加投票项</a>
</p>
<div  >
    <ul class="voteBox" id="voteBox">
        <?php if(!empty($data)):
            foreach($data as $k=>$c){
            ?>
        <li>
            <label>标题</label><input class="text-input larger-input" type="text" name="voteName[]" value="<?php echo $c['votename']; ?>" /><br />
            <label>票数</label><input class="text-input middle-input" type="text" name="voteCount[]" value="<?php echo $c['count']; ?>" />
            <input type="hidden" name="voteid[]" value="<?php echo $c->vid; ?>" />
            
            <img id="vlitS<?php echo $k+1; ?>" class="coverImg" style="margin-top:5px; margin-bottom: 5px;" src="<?php echo (empty($c['litpic']))?ASSETS . 'base/NOIMG.jpg':UPFILE.$filetemp.'/'.$c['litpic']; ?>" />
            <input type="hidden" name="voteLitpic[]" id="vlit<?php echo $k+1; ?>" value="<?php echo $c['litpic']; ?>" />
            <iframe border="no" width="100%" height="60px" src="<?php echo CHtml::normalizeUrl(array('upload/index', 'fname' => '/upload/' . $filetemp,'id'=>$k+1, 'model' => 6)) ?>" ></iframe>
        </li>
        <script type="text/javascript">
        id = '<?php echo $k+1; ?>';    
    </script>
        <?php }else: ?>
        <li>
            <label>标题</label><input class="text-input larger-input" type="text" name="voteName[]" />
            <img id="vlitS1" class="coverImg" style="margin-top:5px; margin-bottom: 5px;" src="<?php echo ASSETS . 'base/NOIMG.jpg'; ?>" />
            <input type="hidden" name="voteid[]" value="0" />
            <input type="hidden" name="voteCount[]" value="0" />
            <input type="hidden" name="voteLitpic[]" id="vlit1" />
            <iframe border="no" width="100%" height="60px" src="<?php echo CHtml::normalizeUrl(array('upload/index', 'fname' => '/upload/' . $filetemp,'id'=>'1', 'model' => 6)) ?>" ></iframe>
        </li>
        <?php endif; ?>
    </ul>
            
</div>
<script type="text/javascript">
function voteLitpic(id,litpic){
         var old = $('#vlit'+id).val();
         
         var path = '/upload/<?php echo $filetemp; ?>/';
         if(old!=''){
         $.ajax({
             type:'post',
             data:'path='+path+old,
             url:'<?php echo CHtml::normalizeUrl(array('channel/deleteCover')); ?>'
         });
         }
         path = path+litpic;
         $('#vlitS'+id).attr('src',path);
         $('#vlit'+id).val(litpic);
}
</script>

pipistrellVote/protected/admin/views/layouts/footer.php
<div id="footer"> <small>
     
      &#169; Copyright 2015 @pipistrell   email:appyouxiang@163.com | <a href="<?php echo CHtml::normalizeUrl(array('site/ShowMail')); ?>">联系开发者</a> </small> </div>

  </div>

pipistrellVote/protected/admin/views/layouts/left.php
<div id="sidebar">
    <div id="sidebar-wrapper" >


      <div id="profile-links"> <br />
        <a href="/index.php" target="_BLANK" style="color:#000;" title="网站前台首页">网站前台首页</a> | <a href="<?php echo Yii::app()->createUrl("site/logout"); ?>" style="color:#000;" >注销</a> </div>
      <ul id="main-nav">
        <li> <a href="#" class="nav-top-item <?php if($this->isType==1)echo 'current'; ?>">系统管理</a>
          <ul>
            <li><a <?php if($this->isSmallType==1 && $this->isType==1)echo 'class="current"'; ?> href="<?php echo Yii::app()->createUrl("Webroot/index",array('isSmallType'=>1)); ?>">站点设置</a></li>
            
          </ul>
        </li>
        <li> <a href="#" class="nav-top-item <?php if($this->isType==9)echo 'current'; ?>">管理员</a>
          <ul>
            <li><a <?php if($this->isSmallType==1 && $this->isType==9)echo 'class="current"'; ?> href="<?php echo Yii::app()->createUrl("jurisdiction/index",array('isSmallType'=>1)); ?>">账户管理</a></li>
          </ul>
        </li>
        
        <li> <a href="#" class="nav-top-item <?php if($this->isType==3)echo 'current'; ?>">广告管理</a>
          <ul>
            <li><a <?php if($this->isType==3 && $this->isSmallType==1)echo 'class="current"'; ?> href="<?php echo CHtml::normalizeUrl(array("Advert/index",'isSmallType'=>1)); ?>">广告管理</a></li>
          </ul>
        </li>
        <li> <a href="#" class="nav-top-item <?php if($this->isType==4)echo 'current'; ?>">栏目管理</a>
          <ul>
            <li><a <?php if($this->isType==4 && $this->isSmallType==1)echo 'class="current"'; ?> href="<?php echo Yii::app()->createUrl("channel/index",array('isSmallType'=>1)); ?>">栏目管理</a></li>
          </ul>
        </li>
        <li>
            <a href="#" class="nav-top-item <?php if($this->isType==5)echo 'current'; ?>">快捷内容管理</a>
          <ul>
              <?php $topChannel = adminSys::_getQuickChannel(); 
                   if($topChannel):
                       foreach($topChannel as $value):
              ?>
            <li><a href="<?php echo Yii::app()->createUrl('listart/index',array('artTopId'=>$value['id'],'isSmallType'=>$value['id'])); ?>"  <?php if($this->isType==5 && $this->isSmallType==$value->id)echo 'class="current"'; ?> ><?php echo $value->typename; ?></a></li>
            <?php endforeach;endif; ?>
          </ul>
        </li>
        <li>
            <a href="#" class="nav-top-item <?php if($this->isType==6)echo 'current'; ?>">数据库管理</a>
            <ul>
            <li><a <?php if($this->isType==6 && $this->isSmallType==1)echo 'class="current"'; ?> href="<?php echo Yii::app()->createUrl("backup/default/index"); ?>">数据库备份</a></li>
            <li><a <?php if($this->isType==6 && $this->isSmallType==1)echo 'class="current"'; ?> href="<?php echo Yii::app()->createUrl("backup/default/Create"); ?>">建立备份</a></li>
            <li><a <?php if($this->isType==6 && $this->isSmallType==1)echo 'class="current"'; ?> href="<?php echo Yii::app()->createUrl("backup/default/Upload"); ?>">上传数据库备份</a></li>
          </ul>
        </li>

      
          </ul>
        
    </div>
  </div>

pipistrellVote/protected/admin/views/layouts/widget_step.php
<link rel="stylesheet" href="<?php echo ASSETS;?>css/widget_step.css" type="text/css" />
<div class="stepInfo">

	<ul>
		<li></li>
		<li></li>
	</ul>
	
	<div class="stepIco stepIco1 <?php if($step==1) echo 'stepIcoSel'; ?>">1
		<div class="stepText">录入挂件信息</div>
	</div>
	
	<div class="stepIco stepIco2 <?php if($step==2) echo 'stepIcoSel'; ?>">2
		<div class="stepText">上传控制文件</div>
	</div>
	
	<div class="stepIco stepIco3 <?php if($step==3) echo 'stepIcoSel'; ?>">3
		<div class="stepText">上传显示文件</div>
	</div>
	
</div>
<br >
<div class="clear"></div>